### ISSUE TITLE
Memory leak with pendingReceipts with continuous PING frames

### ISSUE THREAD

**Issue by DevMcC** [vert-x3/vertx-stomp#76]
### Version

`4.3.7`

### Context

Our applications were having memory issues.
Upon analyzing the heapdump, it appears that the `StompClientConnectionImpl` had accumulated over 58k pending receipts.

I have created a reproducer, that simply creates the StompClient and StompClientConnection.
Using a Timer and Reflection, it prints out the current number of pending receipts every second.
When running this reproducer it appears the `StompClientConnectionImpl` is adding a pending receipt every second.

These receipts come from PING frames, that never get handled.
According to the code, when a PING frame is received, nothing is being done - not even removing the pending receipt.
Due to this the `pendingReceipts` Map is getting bigger and bigger every second.

### Do you have a reproducer?
```kotlin
fun main() {
    val vertx = Vertx.vertx()
    val client = StompClient.create(vertx)
    client.connect(port, host) { connectionResult ->
        println("Connected!")
        val connection = connectionResult.result()

        Timer().schedule(1_000, 1_000) {
            val pendingReceiptsField = connection.javaClass.getDeclaredField("pendingReceipts")
            pendingReceiptsField.trySetAccessible()
            val pendingReceipts = pendingReceiptsField.get(connection) as Map<String, Promise<Void>>

            println("There are currently ${pendingReceipts.size} pending receipts")
        }
    }
}
```

### Screenshots
![image](https://user-images.githubusercontent.com/26748646/214875612-c697dfd9-f814-4748-87b6-0abd4579e559.png)

**Comment by adhesivee** [comment]
It seems something has changed in a later version [here](https://github.com/vert-x3/vertx-stomp/blob/master/src/main/java/io/vertx/ext/stomp/impl/StompClientConnectionImpl.java#L198).
Receipt handler used to be null in some cases. This library consider `PING` as a `Frame` and thus using `send` which creates a non-null field for receiptHandler, which can't be handled because "PING" is just `\n`. And this will make sure this will stack up with every PING
